/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.view;

import br.com.fatec.dao.HospedeDAO;
import br.com.fatec.dao.ReservarDAO;
import br.com.fatec.model.Hospede;
import br.com.fatec.model.Reservar;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author drextar
 */
public class QuitarAluguel extends javax.swing.JInternalFrame {
    ReservarDAO urDao = new ReservarDAO();
    HospedeDAO hospedeDao = new HospedeDAO();

    /**
     * Creates new form EncerraEstadia
     */
    public QuitarAluguel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        qPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuarto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtCvv = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("CPF do Hospede");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor dos Serviços");

        txtServico.setEnabled(false);

        jLabel4.setText("Valor do Quarto");

        txtQuarto.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/imagens/icones/payment-method.png"))); // NOI18N
        jButton1.setText("Efetuar Pagamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Total a Pagar");

        txtTotal.setEnabled(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/imagens/icones/shopping-bag.png"))); // NOI18N
        jButton2.setText("Encerrar Estadia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero do Cartao");

        txtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumKeyTyped(evt);
            }
        });

        jLabel6.setText("CVV");

        jLabel7.setText("Nome do Titular");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCvv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/imagens/icones/undo-button.png"))); // NOI18N
        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qPaneLayout = new javax.swing.GroupLayout(qPane);
        qPane.setLayout(qPaneLayout);
        qPaneLayout.setHorizontalGroup(
            qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qPaneLayout.createSequentialGroup()
                        .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNum, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jButton3)
                            .addGroup(qPaneLayout.createSequentialGroup()
                                .addComponent(txtCvv)
                                .addGap(12, 12, 12)))))
                .addGap(66, 66, 66)
                .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPaneLayout.createSequentialGroup()
                        .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qPaneLayout.createSequentialGroup()
                                .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtServico)
                                    .addGroup(qPaneLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 119, Short.MAX_VALUE)))
                                .addGap(32, 32, 32))
                            .addGroup(qPaneLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtTotal))
                        .addGap(36, 36, 36))
                    .addGroup(qPaneLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton4)
                        .addContainerGap(86, Short.MAX_VALUE))))
        );
        qPaneLayout.setVerticalGroup(
            qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(txtQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(qPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(qPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Hospede hospede = new Hospede();
        if(txtCpf.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo CPF!");
        } else {
            hospede.setCpf(txtCpf.getText());
            try {
                hospede = hospedeDao.buscar(hospede);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro: "
                        + ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BuscaHospede.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (hospede != null) {
                JOptionPane.showMessageDialog(rootPane, "Favor realizar o pagamento dos serviços/diárias pendentes!");            
            } else {            
                JOptionPane.showMessageDialog(rootPane, "Estadia encerrada com sucesso!");
                hide();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Reservar ur = new Reservar();
        if(txtCpf.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo CPF!");
        } else {
            ur.setCpf(txtCpf.getText());
            try {
                ur = urDao.buscarReserva(ur);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro: "
                        + ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BuscaHospede.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (ur != null) {
                txtQuarto.setText(String.valueOf(ur.getValorTotal()));
            } else {            
                JOptionPane.showMessageDialog(rootPane, 
                        "CPF não possui reserva!");
                txtServico.setText("");
                txtTotal.setText("");
                txtQuarto.setText("");
                txtCpf.setText("");
                return;
            }
            
            try {
                ur = urDao.consultarServico(ur);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro: "
                        + ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BuscaHospede.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (ur != null) {
                txtServico.setText(String.valueOf(ur.getValorServico()));
            } else {            
                txtServico.setText("0.0");
            }
            
            txtTotal.setText(String.valueOf(Float.parseFloat(txtServico.getText()) + Float.parseFloat(txtQuarto.getText())));
        }     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txtCpf.getText().equals("") || txtServico.getText().equals("") || txtQuarto.getText().equals("") || txtTotal.getText().equals("") || txtNum.getText().equals("") || txtCvv.getText().equals("") || txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Favor preencher todos os campos de pagamento!");
        } else {
            Reservar ur = new Reservar();
        
            ur.setCpf(txtCpf.getText());
            try {
                urDao.excluirServico(ur);  
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, 
                                "Erro SQL: " + ex.getMessage());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, 
                                "Erro Classe: " +ex.getMessage());
            }
            
            try {
                urDao.excluirEstadia(ur);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, 
                                "Erro SQL: " + ex.getMessage());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, 
                                "Erro Classe: " +ex.getMessage());
            }
            JOptionPane.showMessageDialog(rootPane, "Pagamento realizado com sucesso!");
            limpaDados();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_txtNumKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        hide();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    public void limpaDados(){
        txtCpf.setText("");
        txtNome.setText("");
        txtNum.setText("");
        txtCvv.setText("");
        txtTotal.setText("");
        txtServico.setText("");
        txtQuarto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel qPane;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtCvv;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtQuarto;
    private javax.swing.JTextField txtServico;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
